Updated ldavis.js to be compatible with latest d3.v5
bmabey/pyLDAvis pull request #154
Opened 2019-08-23 19:02 UTC by dtemkin

CHANGED 
     scale.linear(...)
TO
     scaleLinear(...)
==================================================
CHANGED
    .axis(...).scale(...).orient(...) 
TO
    axisLeft (_y_)(...), axisTop(...) (_x_) or axisBottom(...) (_scaleX_) 
==================================================
CHANGED
    d3.scaleordinal(...).domain(...).rangeRoundBands(...)
TO
    d3.scaleBand().domain(...).rangeBands(...).padding(...)
==================================================
CHANGED
    y.rangeBand(...) 
TO
    y.bandwidth(...)
==================================================
REPLACED d3.v3.js with d3.v5.js
==================================================
ADDED:
    optional function parameters that let user specify primary (color1) and 
secondary (color2) colors. (Default colors are originals)

This should also be compatible with d3.v4 but I havent tested it yet.

2019-08-23 20:03 UTC, dtemkin commented
I looked at the errors and they appear to be the result of an issue in pandas. I can attempt to address them if necessary to merge my PR.

2020-10-22 15:44 UTC, bmabey approved these changes

2020-10-22 15:46 UTC, bmabey commented
Could you resolve the conflicts in ldavis.js?

2020-11-16 16:15 UTC, msusol commented
Are these changes still relevant? I can make an attempt to resolve the conflicts in ldavis.js

Is there any other effort to upgrade d3.v3 to d3.v5+ ?

2020-11-25 06:35 UTC, dtemkin commented
@msusol @bmabey Sorry this took me so long to complete. I fixed the references to d3 so that they are specifically referencing d3.v5.min.js or https://d3js.org/d3.v5.js . I believe everything is good to go, but take a look when you get a chance to make sure I am not missing something. 

I also fixed the problems with the travis-ci configuration in which I had to separate the dependencies for python 3.5.

2020-11-26 00:51 UTC, bmabey requested changes
It looks like you maybe forgot to rebase to get the latest changes? Python code changes are happening that seem unrelated to updating to the latest d3.

2020-11-26 00:51 UTC, bmabey commented on pyLDAvis/_prepare.py
> -def _topic_coordinates(mds, topic_term_dists, topic_proportion, start_index=1):
Is there a reason why you changed this line?

2020-11-26 00:51 UTC, bmabey commented on pyLDAvis/_prepare.py
> -                           'topics': range(start_index, K + start_index),
Ditto here.. my guess is that this is an accident...

2020-11-26 00:51 UTC, bmabey commented on pyLDAvis/_prepare.py
> +    return relevance.T.apply(lambda s: s.sort_values(ascending=False).index).head(R)
ditto

2020-11-26 00:51 UTC, bmabey commented on pyLDAvis/_prepare.py
> -                vocab, lambda_step, R, n_jobs, start_index=1):
ditto, I don't see why these changes are needed for this PR

2020-12-02 18:10 UTC, bmabey commented
LGTM, thank you for this @dtemkin!

2020-12-02 18:10 UTC, merged

2020-12-17 16:10 UTC, msusol commented
Thank you!!

2020-12-17 16:12 UTC, msusol commented
Thank you, Dan!

Ben, when will there be a new version tag available?

On Wed, Dec 2, 2020 at 11:10 AM Ben Mabey <notifications@github.com> wrote:

> Merged #154 <https://github.com/bmabey/pyLDAvis/pull/154> into master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bmabey/pyLDAvis/pull/154#event-4063725653>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVPINZMP4ORNTGV7MMGVBLSSZ7JLANCNFSM4IPCPCVQ>
> .
>

2021-02-10 14:23 UTC, msusol commented
Dan,

Please see the recent issues about missing the labels in the d3.v5
rendering.

On Thu, Dec 17, 2020, 9:12 AM Mark Susol <marksusol@gmail.com> wrote:

> Thank you, Dan!
>
> Ben, when will there be a new version tag available?
>
> On Wed, Dec 2, 2020 at 11:10 AM Ben Mabey <notifications@github.com>
> wrote:
>
>> Merged #154 <https://github.com/bmabey/pyLDAvis/pull/154> into master.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/bmabey/pyLDAvis/pull/154#event-4063725653>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAVPINZMP4ORNTGV7MMGVBLSSZ7JLANCNFSM4IPCPCVQ>
>> .
>>
>

2021-02-18 00:48 UTC, msusol commented
See follow up refactoring: #198